name: Build OT Watchdog ZIP

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create clean build folder
        run: |
          mkdir build

          rsync -av \
            --exclude='.git' \
            --exclude='.github' \
            --exclude='tests' \
            ./ build/ot-watchdog/

      - name: Create ZIP
        run: |
          cd build
          zip -r ot-watchdog.zip ot-watchdog

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: ot-watchdog-plugin
          path: build/ot-watchdog.zip
